---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sc1bovu7233/public_html/icia-site
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp package-lock.json $DEPLOYPATH/
    - /bin/cp next.config.js $DEPLOYPATH/
    - cd $DEPLOYPATH && /usr/local/bin/npm install
    - cd $DEPLOYPATH && /usr/local/bin/npm run build
