import { Header } from '@/components/layout/Header'
import { Footer } from '@/components/layout/Footer'
import { FadeIn } from '@/components/Animations'
import { LocalizedLink } from '@/lib/i18n'
import Globus3D from '@/components/Globus3D'

const SECTIONS_FR = [
  { title: "I. L'intelligence artificielle appartient à tous", body: <>L&rsquo;IA n&rsquo;est pas un produit. Elle est une <a href="https://www.oecd.org/en/topics/policy-issues/artificial-intelligence.html" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>transformation civilisationnelle d&rsquo;une portée comparable à l&rsquo;imprimerie ou à l&rsquo;électricité</a>. À ce titre, elle ne peut être abandonnée aux seules logiques du marché. L&rsquo;ICIA affirme que toute personne, toute organisation, tout territoire a le droit d&rsquo;accéder aux savoirs, aux outils et aux débats qui façonnent cette transformation. La <a href="https://www.unesco.org/en/artificial-intelligence/recommendation-ethics" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Recommandation de l&rsquo;UNESCO sur l&rsquo;éthique de l&rsquo;IA</a>, adoptée à l&rsquo;unanimité par 193 États membres en 2021, le pose sans ambiguïté : la protection de la dignité humaine et l&rsquo;équité d&rsquo;accès sont les pierres angulaires de tout cadre éthique sérieux. L&rsquo;accès n&rsquo;est pas un privilège. C&rsquo;est une condition de la démocratie.</> },
  { title: 'II. La souveraineté numérique est une condition de la liberté', body: <>Déléguer la totalité de son infrastructure cognitive à des systèmes étrangers, opaques et non régulés, c&rsquo;est abdiquer une partie de sa souveraineté. L&rsquo;ICIA défend <a href="https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>une approche européenne de l&rsquo;IA</a> fondée sur la transparence des données d&rsquo;entraînement, la connaissance des biais, et la maîtrise des conditions de déploiement. Le <a href="https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Règlement européen sur l&rsquo;intelligence artificielle</a> (Règlement UE 2024/1689), premier cadre législatif complet au monde sur l&rsquo;IA, pose ce principe en droit positif : la confiance ne se décrète pas, elle s&rsquo;organise. Pas par nationalisme étroit, mais parce qu&rsquo;un outil qu&rsquo;on ne comprend pas est un outil dont on devient dépendant, et qu&rsquo;une dépendance non choisie est une forme de servitude.</> },
  { title: 'III. Le collectif est une méthode, pas une posture', body: <>Le mot &laquo;&nbsp;collectif&nbsp;&raquo; dans notre nom n&rsquo;est pas décoratif. Il décrit une épistémologie : nous croyons que la connaissance pertinente sur l&rsquo;IA ne se construit pas dans la solitude d&rsquo;un bureau de recherche, ni dans la verticalité d&rsquo;un cabinet de conseil. Elle se construit dans la friction productive entre disciplines, entre métiers, entre générations, entre usages. Les <a href="https://legalinstruments.oecd.org/api/print?ids=648&lang=fr" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Principes de l&rsquo;OCDE sur l&rsquo;intelligence artificielle</a>, révisés en 2024, le confirment : une IA digne de confiance requiert une gouvernance multi-parties prenantes, adaptative, et ouverte à l&rsquo;ensemble des acteurs de la société. L&rsquo;ICIA est un espace de confrontation intellectuelle rigoureuse et bienveillante, où l&rsquo;ingénieur, le pédagogue, le juriste, l&rsquo;artiste et l&rsquo;entrepreneur apprennent ensemble ce qu&rsquo;aucun d&rsquo;eux ne pourrait apprendre seul.</> },
  { title: 'IV. La pédagogie est un acte politique', body: <>Former, c&rsquo;est choisir ce que les gens seront capables de faire et de refuser. Le <a href="https://www.europarl.europa.eu/topics/en/article/20230601STO93804/eu-ai-act-first-regulation-on-artificial-intelligence" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Règlement européen sur l&rsquo;IA impose, à son Article 4, une obligation d&rsquo;alphabétisation à l&rsquo;IA</a> pour tous les acteurs qui développent ou déploient des systèmes. Mais une formation à l&rsquo;IA qui se limite à l&rsquo;usage des outils sans former au jugement critique, à l&rsquo;éthique et à la compréhension des mécanismes produit des utilisateurs dociles, pas des citoyens éclairés. La <a href="https://www.unesco.org/en/artificial-intelligence/recommendation-ethics" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Recommandation de l&rsquo;UNESCO</a> l&rsquo;énonce avec force : l&rsquo;éducation à l&rsquo;IA doit promouvoir l&rsquo;autonomie, le sens critique et les droits fondamentaux à toutes les étapes du cycle de vie des systèmes. L&rsquo;ICIA considère que toute action pédagogique est une prise de position sur le monde que l&rsquo;on veut construire. Nous choisissons la formation qui émancipe.</> },
  { title: 'V. Le concret prime sur la spéculation', body: <>L&rsquo;ICIA n&rsquo;est pas un think tank. Nous n&rsquo;écrivons pas des rapports qui restent des rapports. Les <a href="https://www.oecd.org/fr/publications/perspectives-de-l-emploi-de-l-ocde-2023_aae5dba0-fr.html" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Perspectives de l&rsquo;emploi de l&rsquo;OCDE 2023</a> l&rsquo;établissent clairement : 27 % des emplois dans les pays de l&rsquo;OCDE correspondent à des professions fortement exposées au risque d&rsquo;automatisation. Ce chiffre n&rsquo;est pas une abstraction théorique. Il désigne des personnes réelles, dans des organisations réelles, confrontées à des décisions réelles. Notre boussole n&rsquo;est pas l&rsquo;état de l&rsquo;art théorique, mais la question de ce qui fonctionne, pourquoi, dans quelles conditions, et pour qui. La rigueur du terrain est au moins aussi exigeante que la rigueur académique.</> },
  { title: "VI. L'artisanat intellectuel contre la production en série", body: <>Il existe une manière industrielle de déployer l&rsquo;IA : répliquer les mêmes solutions dans des contextes différents sans les adapter, vendre des certifications sans construire des compétences, produire du contenu sans produire de la pensée. Kate Crawford, chercheuse à l&rsquo;Université de New York, l&rsquo;a documenté avec rigueur dans son ouvrage <a href="https://yalebooks.yale.edu/book/9780300264630/atlas-of-ai/" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Atlas of AI</a> : l&rsquo;IA n&rsquo;est pas neutre, elle est le produit de choix humains, de rapports de force et de contextes spécifiques qui en déterminent les effets réels. L&rsquo;ICIA s&rsquo;oppose frontalement à toute approche indifférente au contexte. Chaque intervention, chaque programme, chaque outil que nous concevons est pensé pour son terrain particulier. L&rsquo;artisanat intellectuel n&rsquo;est pas une lenteur : c&rsquo;est une exigence de pertinence.</> },
  { title: 'VII. La transparence est notre contrat avec la société', body: <>En tant qu&rsquo;association loi 1901, l&rsquo;ICIA n&rsquo;a pas d&rsquo;actionnaires à satisfaire, pas de valorisation boursière à défendre, pas d&rsquo;intérêt à cacher ses conclusions pour protéger un client. Le <a href="https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Règlement européen sur l&rsquo;IA</a> fait de la transparence une obligation légale pour les systèmes qui interagissent avec les citoyens. L&rsquo;ICIA va plus loin : nous appliquons ce principe non seulement à nos outils mais à notre organisation elle-même. Nous publions ce que nous apprenons. Nous documentons nos erreurs autant que nos réussites. Notre modèle associatif n&rsquo;est pas un détail administratif. Il est la garantie structurelle de notre indépendance. La transparence n&rsquo;est pas une vertu optionnelle : c&rsquo;est le fondement de la confiance.</> },
  { title: "VIII. L'humain au centre n'est pas un slogan", body: <>&laquo;&nbsp;L&rsquo;humain au centre de l&rsquo;IA&nbsp;&raquo; est devenu l&rsquo;une des formules les plus creuses du discours technologique contemporain. Les <a href="https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Lignes directrices éthiques pour une IA digne de confiance</a>, publiées par le Groupe d&rsquo;experts de haut niveau de la Commission européenne, en donnent une définition opérationnelle rigoureuse : sept exigences concrètes, dont la supervision humaine, la robustesse technique, et la non-discrimination. L&rsquo;ICIA refuse d&rsquo;en faire un argument marketing. Placer l&rsquo;humain au centre signifie concrètement : concevoir des systèmes dont les effets sur les personnes sont anticipés, mesurés et assumés ; refuser les automatisations qui dégradent le travail sans créer de valeur ; reconnaître que l&rsquo;IA amplifie autant les inégalités qu&rsquo;elle peut les réduire. Ce n&rsquo;est pas une posture humaniste. C&rsquo;est un programme de travail.</> },
  { title: 'IX. Les territoires ne sont pas des marchés secondaires', body: <>La transformation par l&rsquo;IA ne peut pas se concentrer dans quelques pôles urbains et laisser les territoires intermédiaires sans ressources. Le baromètre publié par Maire-Info en 2025 le quantifie sans détour : <a href="https://www.maire-info.com/intelligence-artificielle/intelligence-artificielle-des-fractures-territoriales-et-un-retard-du-secteur-public--article-30740" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>59 % des habitants de l&rsquo;agglomération parisienne utilisent l&rsquo;IA générative, contre 34 % dans les communes rurales</a>, créant selon ses auteurs une &laquo;&nbsp;France de l&rsquo;IA à plusieurs vitesses&nbsp;&raquo;. Le <a href="https://www.senat.fr/rap/r21-588/r21-588.html" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>rapport du Sénat sur la cohésion numérique dans les territoires</a> dresse le même constat sur l&rsquo;exclusion numérique structurelle et appelle à en faire une priorité nationale dotée de financements pérennes. L&rsquo;ICIA a une vocation territoriale explicite. Nous travaillons là où les ressources manquent, pas seulement là où elles abondent. L&rsquo;inclusion géographique est une dimension à part entière de notre mission.</> },
  { title: "X. Construire sans détruire : l'IA comme choix civilisationnel", body: <>L&rsquo;IA peut accélérer la concentration des richesses, fragiliser le lien social, automatiser la manipulation, étendre la surveillance. Elle peut aussi augmenter les capacités humaines, réduire des inégalités d&rsquo;accès à l&rsquo;expertise, libérer du temps pour ce qui a de la valeur. Ces deux trajectoires ne sont pas équiprobables. Yoshua Bengio, lauréat du prix Turing 2018 et l&rsquo;une des voix scientifiques les plus rigoureuses sur ce sujet, l&rsquo;a posé dans le <a href="https://www.journalofdemocracy.org/ai-and-catastrophic-risk/" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Journal of Democracy</a> : les conséquences de l&rsquo;IA pour la démocratie et l&rsquo;humanité résultent de décisions politiques, économiques et pédagogiques que des acteurs humains prennent tous les jours. L&rsquo;ICIA choisit sa trajectoire. Nous construisons des usages qui renforcent les individus, les collectifs et les institutions plutôt que de les affaiblir. Ce n&rsquo;est pas de l&rsquo;optimisme naïf. C&rsquo;est une responsabilité que nous assumons.</> },
]

const SECTIONS_EN = [
  { title: 'I. Artificial intelligence belongs to everyone', body: <>AI is not a product. It is a <a href="https://www.oecd.org/en/topics/policy-issues/artificial-intelligence.html" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>civilizational transformation comparable in scope to the printing press or electricity</a>. As such, it cannot be left to market forces alone. ICIA affirms that every person, every organization, every territory has the right to access the knowledge, tools and debates that shape this transformation. The <a href="https://www.unesco.org/en/artificial-intelligence/recommendation-ethics" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>UNESCO Recommendation on the Ethics of AI</a>, adopted unanimously by 193 member states in 2021, states it unequivocally: the protection of human dignity and equity of access are the cornerstones of any serious ethical framework. Access is not a privilege. It is a condition of democracy.</> },
  { title: 'II. Digital sovereignty is a condition of freedom', body: <>Delegating one&rsquo;s entire cognitive infrastructure to foreign, opaque and unregulated systems is to abdicate part of one&rsquo;s sovereignty. ICIA defends <a href="https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>a European approach to AI</a> based on transparent training data, knowledge of biases, and control over deployment conditions. The <a href="https://eur-lex.europa.eu/eli/reg/2024/1689/oj/eng" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>European AI Act</a> (EU Regulation 2024/1689), the world&rsquo;s first comprehensive legislative framework on AI, establishes this principle in positive law: trust is not decreed, it is organized. Not through narrow nationalism, but because a tool we do not understand is a tool we become dependent on, and unchosen dependency is a form of servitude.</> },
  { title: 'III. Collective is a method, not a posture', body: <>The word &laquo;&nbsp;collective&nbsp;&raquo; in our name is not decorative. It describes an epistemology: we believe that relevant knowledge about AI is not built in the solitude of a research office, nor in the verticality of a consulting firm. It is built in the productive friction between disciplines, between professions, between generations, between uses. The <a href="https://legalinstruments.oecd.org/api/print?ids=648&lang=fr" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>OECD Principles on Artificial Intelligence</a>, revised in 2024, confirm this: trustworthy AI requires multi-stakeholder, adaptive governance open to all actors in society. ICIA is a space of rigorous and benevolent intellectual confrontation, where the engineer, the teacher, the lawyer, the artist and the entrepreneur learn together what none of them could learn alone.</> },
  { title: 'IV. Pedagogy is a political act', body: <>Training means choosing what people will be capable of doing and refusing. The <a href="https://www.europarl.europa.eu/topics/en/article/20230601STO93804/eu-ai-act-first-regulation-on-artificial-intelligence" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>European AI Act imposes, in Article 4, an AI literacy obligation</a> for all actors who develop or deploy systems. But AI training limited to tool use without training in critical judgment, ethics and understanding of mechanisms produces docile users, not enlightened citizens. The <a href="https://www.unesco.org/en/artificial-intelligence/recommendation-ethics" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>UNESCO Recommendation</a> states it forcefully: AI education must promote autonomy, critical thinking and fundamental rights at all stages of the system lifecycle. ICIA considers that every pedagogical action is a position on the world we want to build. We choose education that emancipates.</> },
  { title: 'V. The concrete takes precedence over speculation', body: <>ICIA is not a think tank. We do not write reports that remain reports. The <a href="https://www.oecd.org/fr/publications/perspectives-de-l-emploi-de-l-ocde-2023_aae5dba0-fr.html" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>OECD Employment Outlook 2023</a> clearly establishes: 27% of jobs in OECD countries correspond to professions highly exposed to automation risk. This figure is not a theoretical abstraction. It refers to real people, in real organizations, facing real decisions. Our compass is not the theoretical state of the art, but the question of what works, why, under what conditions, and for whom. Field rigor is at least as demanding as academic rigor.</> },
  { title: 'VI. Intellectual craftsmanship vs. mass production', body: <>There is an industrial way of deploying AI: replicating the same solutions in different contexts without adapting them, selling certifications without building skills, producing content without producing thought. Kate Crawford, researcher at New York University, has documented this rigorously in her book <a href="https://yalebooks.yale.edu/book/9780300264630/atlas-of-ai/" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Atlas of AI</a>: AI is not neutral, it is the product of human choices, power relations and specific contexts that determine its real effects. ICIA firmly opposes any context-indifferent approach. Every intervention, every program, every tool we design is thought for its specific terrain. Intellectual craftsmanship is not slowness: it is a requirement of relevance.</> },
  { title: 'VII. Transparency is our contract with society', body: <>As a French non-profit association, ICIA has no shareholders to satisfy, no stock market valuation to defend, no interest in hiding its conclusions to protect a client. The <a href="https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>European AI Act</a> makes transparency a legal obligation for systems that interact with citizens. ICIA goes further: we apply this principle not only to our tools but to our organization itself. We publish what we learn. We document our mistakes as much as our successes. Our associative model is not an administrative detail. It is the structural guarantee of our independence. Transparency is not an optional virtue: it is the foundation of trust.</> },
  { title: 'VIII. Human-centered is not a slogan', body: <>&laquo;&nbsp;Human-centered AI&nbsp;&raquo; has become one of the emptiest phrases in contemporary technology discourse. The <a href="https://digital-strategy.ec.europa.eu/en/library/ethics-guidelines-trustworthy-ai" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Ethics Guidelines for Trustworthy AI</a>, published by the European Commission&rsquo;s High-Level Expert Group, provide a rigorous operational definition: seven concrete requirements, including human oversight, technical robustness, and non-discrimination. ICIA refuses to make it a marketing argument. Placing humans at the center concretely means: designing systems whose effects on people are anticipated, measured and assumed; refusing automations that degrade work without creating value; recognizing that AI amplifies inequalities as much as it can reduce them. This is not a humanist posture. It is a work program.</> },
  { title: 'IX. Territories are not secondary markets', body: <>AI transformation cannot concentrate in a few urban hubs and leave intermediate territories without resources. The barometer published by Maire-Info in 2025 quantifies it bluntly: <a href="https://www.maire-info.com/intelligence-artificielle/intelligence-artificielle-des-fractures-territoriales-et-un-retard-du-secteur-public--article-30740" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>59% of residents in the Paris metropolitan area use generative AI, compared to 34% in rural municipalities</a>, creating what its authors call a &laquo;&nbsp;multi-speed AI France&nbsp;&raquo;. The <a href="https://www.senat.fr/rap/r21-588/r21-588.html" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Senate report on digital cohesion in territories</a> draws the same conclusion on structural digital exclusion and calls for it to become a national priority with sustained funding. ICIA has an explicit territorial vocation. We work where resources are lacking, not only where they abound. Geographic inclusion is a full dimension of our mission.</> },
  { title: 'X. Build without destroying: AI as a civilizational choice', body: <>AI can accelerate wealth concentration, weaken social bonds, automate manipulation, extend surveillance. It can also augment human capabilities, reduce inequalities in access to expertise, free up time for what has value. These two trajectories are not equiprobable. Yoshua Bengio, 2018 Turing Award laureate and one of the most rigorous scientific voices on this subject, stated it in the <a href="https://www.journalofdemocracy.org/ai-and-catastrophic-risk/" target="_blank" rel="noopener noreferrer" style={{ color: '#3886c1', textDecoration: 'underline', textUnderlineOffset: '3px' }}>Journal of Democracy</a>: the consequences of AI for democracy and humanity result from political, economic and pedagogical decisions that human actors make every day. ICIA chooses its trajectory. We build uses that strengthen individuals, collectives and institutions rather than weakening them. This is not naive optimism. It is a responsibility we assume.</> },
]

export default function ManifestePage({ params }: { params: { lang: string } }) {
  const lang = (params.lang === 'en' ? 'en' : 'fr') as 'fr' | 'en'
  const sections = lang === 'en' ? SECTIONS_EN : SECTIONS_FR

  return (
    <>
      <Header />
      <main style={{ paddingTop: '64px' }}>

        {/* Hero */}
        <section style={{ background: '#ffffff', padding: 'clamp(64px, 8vw, 100px) 0 clamp(40px, 6vw, 80px)' }}>
          <div className="container-mentivis">
            <div className="manifeste-hero-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '64px', alignItems: 'start' }}>
              <div>
                <FadeIn>
                  <p className="eyebrow">ICIA</p>
                  <h1 className="t-display text-primary" style={{ marginBottom: '20px' }}>
                    {lang === 'fr' ? 'Manifeste' : 'Manifesto'}
                  </h1>
                  <p className="t-lead" style={{ maxWidth: '560px', marginBottom: '24px' }}>
                    {lang === 'fr'
                      ? "L'ICIA est né d'un constat simple et d'une exigence radicale : l'intelligence artificielle ne peut pas rester la chose de quelques-uns. Ni la propriété exclusive des grandes firmes technologiques, ni le monopole d'une élite académique déconnectée du réel. Ce manifeste est notre contrat avec le monde."
                      : 'ICIA was born from a simple observation and a radical demand: artificial intelligence cannot remain the domain of the few. Neither the exclusive property of large technology firms, nor the monopoly of an academic elite disconnected from reality. This manifesto is our contract with the world.'}
                  </p>
                  <p className="t-lead" style={{ maxWidth: '560px' }}>
                    {lang === 'fr'
                      ? 'Il engage ce que nous sommes, ce que nous refusons, et ce que nous construisons.'
                      : 'It commits what we are, what we refuse, and what we build.'}
                  </p>
                </FadeIn>
              </div>
              <FadeIn delay={0.2}>
                <div className="globus3d-wrap" style={{ display: 'flex', justifyContent: 'center' }}>
                  <Globus3D size={406} />
                </div>
              </FadeIn>
            </div>
          </div>
        </section>

        {/* Sections */}
        <section style={{ background: '#f5f5f5', padding: 'var(--section-gap) 0' }}>
          <div className="container-mentivis" style={{ maxWidth: '800px' }}>
            {sections.map((s, i) => (
              <FadeIn key={i} delay={i * 0.05}>
                <div style={{ marginBottom: i < sections.length - 1 ? '40px' : '0' }}>
                  <h2 className="t-title text-primary" style={{ marginBottom: '12px' }}>
                    {s.title}
                  </h2>
                  <p className="t-lead manifeste-body">{s.body}</p>
                </div>
              </FadeIn>
            ))}
            <FadeIn delay={0.5}>
              <div style={{ marginTop: '48px', borderTop: '1px solid var(--border-light)', paddingTop: '32px' }}>
                <h3 style={{ fontSize: '15px', fontWeight: 500, color: '#000', marginBottom: '8px' }}>
                  {lang === 'fr' ? 'Note sur les sources' : 'Note on sources'}
                </h3>
                <p className="t-caption">
                  {lang === 'fr'
                    ? "Chaque lien renvoie à une source primaire ou institutionnelle : textes officiels de la Commission européenne, de l'OCDE, de l'UNESCO, travaux parlementaires du Sénat français, recherches académiques publiées. Aucune source partisane, aucun blog, aucun média d'opinion."
                    : 'Each link refers to a primary or institutional source: official texts of the European Commission, OECD, UNESCO, French Senate parliamentary work, published academic research. No partisan sources, no blogs, no opinion media.'}
                </p>
                <p className="t-caption" style={{ marginTop: '32px', fontStyle: 'italic' }}>
                  {lang === 'fr'
                    ? "Institut Collectif de l'Intelligence Artificielle, association loi 1901"
                    : 'Institut Collectif de l\'Intelligence Artificielle, French non-profit association'}
                </p>
              </div>
            </FadeIn>
          </div>
        </section>

        <section style={{ background: '#f5f5f5', padding: '0 0 var(--section-gap) 0' }}>
          <div className="container-mentivis">
            <FadeIn>
              <LocalizedLink href="/contact" className="btn-pill btn-black">
                {lang === 'fr' ? 'Nous contacter' : 'Contact us'}
                <svg className="btn-chevron" viewBox="0 0 14 14" fill="none"><path d="M5.25 2.625L9.625 7L5.25 11.375" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>
              </LocalizedLink>
            </FadeIn>
          </div>
        </section>

      </main>
      <style dangerouslySetInnerHTML={{ __html: `@media (max-width:1080px){.globus3d-wrap{max-width:420px!important;margin-left:auto;margin-right:auto}}@media (max-width:870px){.globus3d-wrap{max-width:340px!important}}@media (max-width:768px){.manifeste-hero-grid{grid-template-columns:1fr!important;gap:32px!important}.manifeste-hero-grid>*{min-width:0!important;overflow:hidden}.manifeste-body{font-size:16px!important}.globus3d-wrap{max-width:300px!important}}@media (max-width:480px){.globus3d-wrap{max-width:250px!important}}` }} />
      <Footer />
    </>
  )
}
