import json

content = {
  # Layout / SEO
  "layout.seo.title.default": "Marius IA | Institut Conseil IA - Diagnostic, Formation, Transformation",
  "layout.seo.title.template": "%s | Marius IA",
  "layout.seo.description": "Marius IA, l'institut collectif de l'IA. Conseil en stratégie IA et conformité AI Act pour PME, ETI et organisations françaises. Diagnostic, formations, transformation. Marseille.",
  "layout.seo.keywords": "conseil IA, intelligence artificielle, AI Act, conformité IA, transformation IA, PME, ETI, formation IA, audit IA, gouvernance IA, Marseille, France",
  "layout.seo.author": "Mentivis SAS",
  "layout.seo.creator": "Mentivis SAS",
  "layout.seo.publisher": "Mentivis SAS",
  "layout.og.title": "Marius IA | Institut Conseil IA - Diagnostic, Formation, Transformation",
  "layout.og.description": "Conseil en stratégie IA et conformité AI Act. Accompagnement des organisations françaises : diagnostic, formations, transformation. Marseille.",
  "layout.og.site_name": "Marius IA - Institut Collectif de l'IA",
  "layout.og.image.alt": "Marius IA - Institut Collectif de l'IA",
  "layout.twitter.title": "Marius IA | Institut Conseil IA",
  "layout.twitter.description": "Conseil en stratégie IA et conformité AI Act pour PME, ETI et organisations.",
  "layout.ld_json.org.name": "Marius IA",
  "layout.ld_json.org.alternate_name": "Institut Collectif de l'IA",
  "layout.ld_json.org.description": "Institut de conseil en intelligence artificielle. Accompagnement des organisations dans leur transformation IA avec indépendance et résultats mesurables.",
  "layout.ld_json.org.contact_type": "customer service",
  "layout.ld_json.org.available_language.fr": "French",
  "layout.ld_json.org.available_language.en": "English",
  "layout.ld_json.org.parent_name": "Mentivis SAS",
  "layout.ld_json.org.location.name": "Campus Cyber.AI Euromed",
  "layout.ld_json.org.location.city": "Marseille",
  "layout.ld_json.website.name": "Marius IA - Institut Collectif de l'IA",
  "layout.ld_json.website.description": "Conseil en stratégie IA et conformité AI Act pour PME et organisations françaises.",
  "layout.ld_json.breadcrumb.home": "Accueil",

  # Header
  "header.nav.pour_qui": "Pour qui ?",
  "header.nav.offres": "Offres",
  "header.nav.a_propos": "À propos",
  "header.nav.nos_principes": "Nos principes",
  "header.cta": "Contactez Marius IA !",
  "header.aria.menu": "Menu",
  "header.aria.close_submenu": "Fermer le sous-menu",
  "header.aria.open_submenu": "Ouvrir le sous-menu",
  "header.submenu.pour_qui.entreprises": "Entreprises",
  "header.submenu.pour_qui.professions_liberales": "Professions libérales",
  "header.submenu.pour_qui.ecoles": "Écoles, CFA, Universités",
  "header.submenu.pour_qui.industries_creatives": "Industries créatives",
  "header.submenu.pour_qui.collectivites": "Collectivités et administrations",
  "header.submenu.pour_qui.grand_public": "Grand public",
  "header.submenu.offres.diagnostic": "Diagnostic",
  "header.submenu.offres.formations": "Formations",
  "header.submenu.offres.transformation": "Transformation",
  "header.submenu.offres.partenaire": "Partenaire",

  # Footer
  "footer.tagline": "L'institut collectif de l'IA",
  "footer.by": "by",
  "footer.location.prefix": "Campus",
  "footer.location.city": "Marseille",
  "footer.column.pour_qui": "Pour qui ?",
  "footer.column.offres": "Offres",
  "footer.column.a_propos": "À propos",
  "footer.column.legal": "Légal",
  "footer.about.qui_sommes_nous": "Qui sommes-nous",
  "footer.about.expertises": "Expertises",
  "footer.legal.mentions": "Mentions légales",
  "footer.legal.confidentialite": "Confidentialité",
  "footer.legal.cookies": "Gestion des cookies",
  "footer.legal.cgv": "CGV",
  "footer.cookies.loading": "Chargement en cours...",
  "footer.copyright": "© {year} Marius IA · Mentivis. Tous droits réservés.",
  "footer.social.linkedin_aria": "LinkedIn",
  "footer.social.instagram_aria": "Instagram",

  # Speed Banner
  "speed_banner.text": "Page chargée en {seconds}s",

  # Not Found
  "not_found.title": "404",
  "not_found.heading": "Oups. Cette page s'est envolée.",
  "not_found.body": "On a cherch' partout... Elle a peut-être été mangée par un algorithme mutant.",
  "not_found.cta_home": "Retour à l'accueil",
  "not_found.cta_contact": "On vous aide ?",
  "not_found.footer": "L'IA fait parfois des siennes. On comprend.",

  # Homepage
  "homepage.hero.label": "Institut de l'IA · Campus Cyber.AI, Marseille",
  "homepage.hero.title": "Tout le monde parle d'IA.\nNous vous aidons à faire les bons choix.",
  "homepage.hero.subtitle": "Diagnostic, formation, transformation.",
  "homepage.hero.body": "Des missions cadrées, des résultats mesurables, aucun conflit d'intérêt avec un éditeur ou un intégrateur.",
  "homepage.hero.cta": "C'est pour qui ?",
  "homepage.piliers.title": "Trois principes. Aucune exception.",
  "homepage.piliers.1.title": "Indépendance totale",
  "homepage.piliers.1.desc": "Aucun lien avec des éditeurs ou des intégrateurs. Nos recommandations ne servent que vos intérêts.",
  "homepage.piliers.2.title": "Résultats mesurables",
  "homepage.piliers.2.desc": "Chaque engagement est cadré, suivi, évalué. Vous savez exactement où vous en êtes à chaque étape.",
  "homepage.piliers.3.title": "Conformité AI Act intégrée",
  "homepage.piliers.3.desc": "Le cadre réglementaire européen est pris en compte dans chaque mission. Pas comme une contrainte. Comme une exigence de sérieux.",
  "homepage.pour_qui.title": "Pour qui ?",
  "homepage.pour_qui.subtitle": "Une organisation, des enjeux. Une réponse adaptée. Nos interventions sont conçues et adaptées selon votre contexte et vos besoins.",
  "homepage.pour_qui.1.title": "PME et ETI",
  "homepage.pour_qui.1.desc": "Structurer votre approche avant que les obligations ne s'imposent. L'IA redessine les organisations et transforme les métiers plus vite que prévu. Intégrer les bons outils, former vos équipes et anticiper les exigences de l'AI Act relève désormais d'une décision stratégique. Nous vous aidons à le faire avec méthode et efficacité.",
  "homepage.pour_qui.2.title": "Professions libérales",
  "homepage.pour_qui.2.desc": "Votre expertise n'est pas remplaçable. Mais elle va changer de forme. L'IA entre dans le droit, la médecine, la comptabilité et l'architecture avec une vitesse que peu de cabinets ont anticipée. Comprendre ce qui relève de l'outil, ce qui relève de votre responsabilité, et ce que vous pouvez déléguer sans risque : c'est exactement ce dont vous avez besoin pour décider en confiance.",
  "homepage.pour_qui.3.title": "Écoles, CFA, Universités",
  "homepage.pour_qui.3.desc": "Rendre vos cursus pertinents dans un monde qui a changé. L'arrivée de l'IA dans tous les secteurs nécessite de repenser les formations actuelles et les façons de faire. Nouvelles filières, formation des formateurs, intégration pédagogique : nous intervenons à chaque niveau, avec une approche constructive et pragmatique.",
  "homepage.pour_qui.4.title": "Industries créatives",
  "homepage.pour_qui.4.desc": "Créer avec l'IA sans y perdre son identité. Nouveaux workflows, nouveaux outils, nouveaux droits à comprendre et à défendre. L'IA ouvre des espaces créatifs réels. Elle pose aussi des questions auxquelles vous avez le droit d'exiger des réponses claires. Nous vous aidons à trouver votre position, dans les deux sens du terme.",
  "homepage.pour_qui.5.title": "Collectivités et administrations",
  "homepage.pour_qui.5.desc": "L'IA au service du public, avec les bons garde-fous. Inclusion numérique, transformation des services, observation territoriale. L'IA peut renforcer l'efficacité et l'équité des services publics. À condition de l'aborder avec rigueur éthique et indépendance. C'est exactement ce que nous apportons.",
  "homepage.pour_qui.6.title": "Grand public",
  "homepage.pour_qui.6.desc": "Comprendre l'IA. L'utiliser. Ne pas se faire avoir. Des ateliers accessibles, sans prérequis techniques, pour toutes celles et ceux qui veulent comprendre ce qui change dans leur quotidien. L'IA n'est pas réservée à ceux qui ont déjà tout. Ni à ceux qui savent déjà tout.",
  "homepage.offres.title": "Les offres",
  "homepage.offres.subtitle": "Chaque mission est calibrée. Aucune approche générique, aucun package vendu à la chaîne.",
  "homepage.offres.1.num": "01",
  "homepage.offres.1.title": "Savoir où vous en êtes. Décider où aller.",
  "homepage.offres.1.subtitle": "Diagnostic IA et AI Act",
  "homepage.offres.1.desc": "Vos usages IA cartographiés. Vos risques réglementaires identifiés. Vos cas d'usage prioritaires évalués et hiérarchisés. À l'issue de la mission, vous disposez d'une feuille de route sur 12 mois et d'un rapport de conformité présentable à votre CODIR.",
  "homepage.offres.1.price": "À partir de 1 500 euros",
  "homepage.offres.1.duration": "4 à 6 semaines",
  "homepage.offres.2.num": "02",
  "homepage.offres.2.title": "Former vos équipes, pas une audience.",
  "homepage.offres.2.subtitle": "Formations et Acculturation",
  "homepage.offres.2.desc": "Chaque programme est construit autour des réalités métier de vos collaborateurs. Un responsable commercial, un DRH et un responsable logistique n'ont pas les mêmes enjeux. Leurs formations non plus. De la demi-journée de sensibilisation au parcours sur 5 jours, chaque format est conçu pour produire un effet réel.",
  "homepage.offres.2.price": "À partir de 750 euros",
  "homepage.offres.2.duration": "Demi-journée à 5 jours",
  "homepage.offres.3.num": "03",
  "homepage.offres.3.title": "Une transformation à votre rythme.",
  "homepage.offres.3.subtitle": "Transformation IA",
  "homepage.offres.3.desc": "Gouvernance IA, montée en compétences, pilotage des prestataires, conformité AI Act. Un accompagnement sur mesure, avec des résultats mesurables dès les premiers mois. Vous gardez la main sur chaque décision, à chaque étape.",
  "homepage.offres.3.price": "À partir de 2 500 euros",
  "homepage.offres.3.duration": "6 à 12 mois",
  "homepage.offres.4.num": "04",
  "homepage.offres.4.title": "Un expert disponible quand l'IA touche vos sujets.",
  "homepage.offres.4.subtitle": "Partenaire IA",
  "homepage.offres.4.desc": "Veille réglementaire continue, relecture de projets, alertes AI Act, conseil ponctuel. Un partenaire indépendant, disponible au moment où vous en avez besoin. Trois niveaux d'engagement selon votre rythme et vos enjeux.",
  "homepage.offres.4.price": "À partir de 750 euros par mois",
  "homepage.offres.4.duration": "3 niveaux",
  "homepage.contact.label": "Parlons de votre projet",
  "homepage.contact.heading": "Prêt à vous lancer ?",
  "homepage.contact.body": "Planifions un premier échange pour comprendre vos enjeux et voir comment nous pouvons vous aider.",
  "homepage.contact.cta": "Contactez-nous",
  "homepage.nav.accueil": "Accueil",
  "homepage.nav.piliers": "3 Piliers",
  "homepage.nav.pour_qui": "Pour qui ?",
  "homepage.nav.offres": "Offres",
  "homepage.nav.contact": "Contact",
}

with open('/Users/stv/Documents/zed/icia/content/site.txt', 'w') as f:
    for key, value in content.items():
        f.write(f'# {key}\n')
        f.write(f'{value}\n\n')

print(f"Written {len(content)} keys")
