content = {
  # Offres shared
  "offres.nav.diagnostic": "Diagnostic",
  "offres.nav.formations": "Formations",
  "offres.nav.transformation": "Transformation",
  "offres.nav.partenaire": "Partenaire",
  "offres.shared.retour": "← Retour",
  "offres.shared.cta.contact": "Contactez-nous",
  "offres.shared.cta.contact_mobile": "Échanger",
  "offres.shared.cta.retour": "Retour à l'accueil",
  "offres.shared.cta.retour_mobile": "Retour",

  # Diagnostic
  "offres.diagnostic.num": "OFFRE 01",
  "offres.diagnostic.title": "Diagnostic IA & AI Act",
  "offres.diagnostic.subtitle": "Porte entree universelle",
  "offres.diagnostic.promesse.title": "Promesse",
  "offres.diagnostic.promesse.body": "En {duree}, vous savez exactement où vous en êtes, où vous pouvez aller, et ce que l'AI Act vous impose concrètement — avec une feuille de route prête à exécuter.",
  "offres.diagnostic.contenu.title": "Contenu livre",
  "offres.diagnostic.contenu.1": "Cartographie des usages IA actuels (outils, données, processus)",
  "offres.diagnostic.contenu.2": "Mesure de maturité IA : gouvernance, culture, compétences, infrastructure",
  "offres.diagnostic.contenu.3": "Analyse risques AI Act : classification, obligations haut risque, GPAI, RGPD",
  "offres.diagnostic.contenu.4": "Identification de 3 à 5 cas d'usage prioritaires avec estimation du ROI",
  "offres.diagnostic.contenu.5": "Feuille de route 12 mois : quick wins + chantier structurants",
  "offres.diagnostic.contenu.6": "Restitution en comité de direction avec rapport exécutif",
  "offres.diagnostic.exemple.title": "Exemple",
  "offres.diagnostic.exemple.contexte": "PME logistique 80 personnes (Marseille)",
  "offres.diagnostic.exemple.desc": "Un transporteur régional utilise ChatGPT de manière informelle, sans politique IA, inquiet du RGPD et de la concurrence. Objectif : structurer une approche IA sans risque.",
  "offres.diagnostic.exemple.phase.1": "Interviews dirigeant, DAF, responsable operations, DSI",
  "offres.diagnostic.exemple.phase.2": "Analyse des données, outils en place, cartographie risques AI Act",
  "offres.diagnostic.exemple.phase.3": "Formalisation cas d'usage (tournées optimisées, service client IA, reporting auto)",
  "offres.diagnostic.exemple.phase.4": "Rédaction feuille de route + rapport de conformité",
  "offres.diagnostic.exemple.phase.5": "Restitution CODIR - décision de lancement offre 03",
  "offres.diagnostic.levier.title": "Levier",
  "offres.diagnostic.levier.body": "AI Act en vigueur août {annee} — Urgence réglementaire = achat immédiat — Ticket décidable par CEO/DAF seul (à partir de {montant} euros)",

  # Formations
  "offres.formations.num": "OFFRE 02",
  "offres.formations.title": "Formations & Acculturation IA",
  "offres.formations.subtitle": "Volume & Financement",
  "offres.formations.promesse.title": "Promesse",
  "offres.formations.promesse.body": "Vos équipes utilisent déjà l'IA, souvent sans le savoir, parfois sans sécurité. On fait en sorte qu'elles le fassent bien, en lien avec leur métier, dans un cadre sécurisé.",
  "offres.formations.catalogue.title": "Catalogue de programmes",
  "offres.formations.catalogue.header.programme": "Programme",
  "offres.formations.catalogue.header.contenu": "Contenu",
  "offres.formations.catalogue.header.duree": "Duree",
  "offres.formations.catalogue.1.nom": "IA par métiers",
  "offres.formations.catalogue.1.contenu": "Managers, commerciaux, RH, finance, support client, logistique",
  "offres.formations.catalogue.1.duree": "1 jour",
  "offres.formations.catalogue.2.nom": "IA & sécurité",
  "offres.formations.catalogue.2.contenu": "Risques, données personnelles, arnaques, RGPD, bonnes pratiques",
  "offres.formations.catalogue.2.duree": "1/2 journée",
  "offres.formations.catalogue.3.nom": "IA & esprit critique",
  "offres.formations.catalogue.3.contenu": "Comprendre les LLM, biais, hallucinations, limites des outils",
  "offres.formations.catalogue.3.duree": "1/2 journée",
  "offres.formations.catalogue.4.nom": "Modules écoles/CFA",
  "offres.formations.catalogue.4.contenu": "Cours structurés, TD, cas pratiques pour établissements",
  "offres.formations.catalogue.4.duree": "Sur mesure",
  "offres.formations.catalogue.5.nom": "Parcours emploi IA",
  "offres.formations.catalogue.5.contenu": "Socle numérique + IA métier + badge de compétences",
  "offres.formations.catalogue.5.duree": "3 à 5 jours",
  "offres.formations.catalogue.6.nom": "Formation formateurs",
  "offres.formations.catalogue.6.contenu": "Former les équipes internes ou intervenants partenaires",
  "offres.formations.catalogue.6.duree": "2 jours",
  "offres.formations.exemple.title": "Exemple",
  "offres.formations.exemple.contexte": "CFA BTP Marseille (120 apprentis)",
  "offres.formations.exemple.desc": "Un CFA BTP veut intégrer l'IA dans ses formations sans savoir comment. Les formateurs ne connaissent pas les outils. Les apprentis utilisent déjà l'IA pour leurs devoirs.",
  "offres.formations.exemple.phase.1": "Audit de la maquette pédagogique existante (2 jours)",
  "offres.formations.exemple.phase.2": "Co-construction de 3 modules IA métier : mètres augmentés, IA & sécurité chantier, reporting",
  "offres.formations.exemple.phase.3": "Formation des formateurs (2 jours)",
  "offres.formations.exemple.phase.4": "Livraison des supports + badges de compétences associés",
  "offres.formations.exemple.phase.5": "Accompagnement sur 3 mois à la mise en place",

  # Transformation
  "offres.transformation.num": "OFFRE 03",
  "offres.transformation.title": "Transformation IA",
  "offres.transformation.subtitle": "Programme 6-12 mois",
  "offres.transformation.promesse.title": "Promesse",
  "offres.transformation.promesse.body": "On vous aide à faire passer l'IA de l'expérimentation à la pratique quotidienne - sans casser votre organisation, sans dépendre d'un seul prestataire, avec des résultats mesurables tous les 3 mois.",
  "offres.transformation.apports.title": "Ce que Mentivis apporte",
  "offres.transformation.apports.1": "Gouvernance IA : création du comité IA, charte d'usage, référent interne formé",
  "offres.transformation.apports.2": "Plan de compétences : cartographie des besoins par rôle, parcours de montée en compétences",
  "offres.transformation.apports.3": "Change management : communication interne, ateliers d'adhésion, coaching des managers",
  "offres.transformation.apports.4": "Conformité AI Act + RGPD : mise en cohérence des usages avec les obligations légales",
  "offres.transformation.apports.5": "Pilotage des partenaires techniques (Flowt ou autres) : Mentivis arbitre, contrôle, valide",
  "offres.transformation.apports.6": "Jalons de mesure d'impact tous les trimestres - KPI définis en amont, restitution CODIR",
  "offres.transformation.exemple.title": "Exemple",
  "offres.transformation.exemple.contexte": "ETI services 350 personnes",
  "offres.transformation.exemple.desc": "Une ETI de services aux entreprises a réalisé un diagnostic. 3 cas d'usage prioritaires identifiés : automatisation du support client, IA dans la prospection commerciale, génération de rapports. La direction veut déployer sans risque sur 9 mois.",
  "offres.transformation.exemple.phase.1": "Mise en place gouvernance IA, charte, formation CODIR",
  "offres.transformation.exemple.phase.2": "Deploiement support client IA avec Flowt sous pilotage Mentivis",
  "offres.transformation.exemple.phase.3": "Formation equipes commerciales, deploiement IA prospection",
  "offres.transformation.exemple.phase.4": "Automatisation reporting, mesure d'impact, ajustement",
  "offres.transformation.exemple.phase.5": "Bilan, ROI mesure, feuille de route phase 2",

  # Partenaire
  "offres.partenaire.num": "OFFRE 04",
  "offres.partenaire.title": "Partenaire support long terme",
  "offres.partenaire.subtitle": "Abonnement",
  "offres.partenaire.promesse.title": "Promesse",
  "offres.partenaire.promesse.body": "Un partenaire indépendant pour vous aider à décider sur l'IA, en continu - veille, conseil, arbitrage, alerte réglementaire. Votre numéro à appeler quand l'IA touche vos sujets.",
  "offres.partenaire.niveaux.title": "3 niveaux d'abonnement",
  "offres.partenaire.niveaux.1.nom": "Essentiel",
  "offres.partenaire.niveaux.1.1": "Veille réglementaire IA personnalisée",
  "offres.partenaire.niveaux.1.2": "2h office hours",
  "offres.partenaire.niveaux.1.3": "Alertes AI Act",
  "offres.partenaire.niveaux.2.nom": "Stratégique",
  "offres.partenaire.niveaux.2.1": "Tout Essentiel",
  "offres.partenaire.niveaux.2.2": "Relecture projets IA",
  "offres.partenaire.niveaux.2.3": "Revue prestataires techniques",
  "offres.partenaire.niveaux.2.4": "4h office hours",
  "offres.partenaire.niveaux.3.nom": "Dirigeant",
  "offres.partenaire.niveaux.3.1": "Tout Stratégique",
  "offres.partenaire.niveaux.3.2": "1 comité IA/trimestre",
  "offres.partenaire.niveaux.3.3": "Accès événements Institut",
  "offres.partenaire.niveaux.3.4": "Priorité diagnostics",
  "offres.partenaire.approche.title": "Notre approche",
  "offres.partenaire.approche.body": "Zero dépendance : 100% conseil pur, aucune sous-traitance technique requise",
}

with open('/Users/stv/Documents/zed/icia/content/site.txt', 'a') as f:
    for key, value in content.items():
        f.write(f'# {key}\n')
        f.write(f'{value}\n\n')

print(f"Appended {len(content)} keys")
