content = {
  # À propos
  "a_propos.label": "À propos",
  "a_propos.title": "Construire des solutions adaptées\nexactement à votre besoin,\nvotre métier, votre structure.",
  "a_propos.paragraph.1": "Marius IA est aux systèmes d'intelligence artificielle ce que les architectes sont aux bâtiments : définir le besoin, évaluer l'impact, construire la solution avec les experts adaptés.",
  "a_propos.paragraph.2": "Notre rôle est d'accompagner les organisations à intégrer l'intelligence artificielle de manière structurée, conforme et pérenne. Nous intervenons de la formation des acteurs jusqu'à la conception, la construction et l'orchestration de systèmes d'IA opérationnels.",
  "a_propos.paragraph.3": "Marius IA est porté par Mentivis, depuis le Campus Cyber.AI Euromed de Marseille.",
  "a_propos.institut.label": "L'Institut Collectif de l'IA",
  "a_propos.institut.title": "Un bien et une fois communs",
  "a_propos.institut.paragraph.1": "L'Institut Collectif de l'IA est une association en cours de développement. Sa mission : rendre accessibles à tous les compétences nécessaires pour comprendre et maîtriser l'IA. Un lieu, une plateforme, un réseau d'experts. Porté par la conviction que l'intelligence artificielle ne doit pas rester entre les mains de quelques-uns.",
  "a_propos.institut.mission_title": "Mission et vision",
  "a_propos.institut.mission": "Permettre à tous de prendre des décisions éclairées face à l'IA et de bénéficier de ses avancées.",
  "a_propos.institut.vision": "Notre vision : une transformation IA lisible, maîtrisée et alignée avec les valeurs de ceux qui la conduisent.",
  "a_propos.campus.title": "Campus Cyber.AI",
  "a_propos.campus.paragraph": "Basés au Campus Cyber.AI Euromed, nous évoluons au cœur d'un écosystème actif dédié à la cybersécurité et à l'intelligence artificielle. Un ancrage concret, dans une ville qui assume sa transformation.",
  "a_propos.cta": "Contactez-nous",

  # Contact
  "contact.label": "Contact",
  "contact.title": "Un projet, une question, une urgence réglementaire.",
  "contact.subtitle": "Nous répondons dans les 48 heures.",
  "contact.form.prenom": "Prénom",
  "contact.form.nom": "Nom",
  "contact.form.email": "Votre adresse email",
  "contact.form.organisation": "Votre organisation",
  "contact.form.message": "Votre message",
  "contact.form.message_optional": "(facultatif)",
  "contact.form.consent": "J'accepte de recevoir des informations de Marius IA, conformément à la politique de confidentialité.",
  "contact.form.submit": "Envoyer",
  "contact.form.submitting": "Envoi en cours...",
  "contact.success.title": "Message envoyé !",
  "contact.success.body": "Nous avons bien reçu votre demande. Nous vous répondrons dans les 48h.",
  "contact.success.retour": "Retour à l'accueil",
  "contact.error.default": "Une erreur est survenue. Veuillez réessayer ou nous contacter directement.",
  "contact.adresse.title": "Campus Cyber.AI Euromed Marseille",
  "contact.adresse.ligne": "4 Bd Euroméditerranée, Quai d'Arenc, 13002 Marseille",
  "contact.adresse.itineraire": "Itinéraire sur OpenStreetMap",
  "contact.adresse.site": "campuscyber.fr",

  # Expertises
  "expertises.label": "Expertises",
  "expertises.title": "Ce que nous\nsavons faire !",
  "expertises.subtitle": "Une expertise construite sur le terrain, mobilisable selon vos besoins.",
  "expertises.competences_title": "Compétences",
  "expertises.competence.1.title": "Audit IA et conformité AI Act",
  "expertises.competence.1.desc": "Cartographie des usages et des risques. Analyse de la maturité organisationnelle. Évaluation de la conformité réglementaire. Préparation aux obligations de l'AI Act européen.",
  "expertises.competence.2.title": "Formation et acculturation des équipes",
  "expertises.competence.2.desc": "Programmes sur mesure par métier, par secteur, par niveau de maturité. Sensibilisation, montée en compétences, formation des formateurs.",
  "expertises.competence.3.title": "Pilotage de la transformation IA",
  "expertises.competence.3.desc": "Gouvernance, sélection et encadrement des prestataires, suivi des résultats sur la durée. Un accompagnement structuré qui ne disparaît pas après la première livrable.",
  "expertises.competence.4.title": "Veille et conseil en continu",
  "expertises.competence.4.desc": "Suivi réglementaire, alertes AI Act, relecture de projets, conseil ponctuel. Un expert disponible au bon moment, pas seulement au démarrage.",
  "expertises.cta": "Discuter de votre projet",

  # Actualités
  "actualites.title": "Actualités",
  "actualites.subtitle": "Suivez l'actualite de l'ICIA : evenements, publications, partenariats et reflexions sur l'IA.",
  "actualites.article.non_trouve": "Article non trouvé",
  "actualites.article.inexistant": "Cet article n'existe pas.",
  "actualites.article.retour": "Retour aux actualités",
  "actualites.article.retour_liste": "← Retour aux actualités",
  "actualites.article.precedent": "Article précédent",
  "actualites.article.suivant": "Article suivant",

  # Mentions légales
  "mentions_legales.title": "Mentions légales",
  "mentions_legales.editeur.title": "Éditeur du site",
  "mentions_legales.editeur.nom": "Mentivis SAS",
  "mentions_legales.editeur.forme": "Société par actions simplifiée au capital de dix mille euros",
  "mentions_legales.editeur.siege": "Siège social : 60 rue François 1er, 75008 Paris",
  "mentions_legales.editeur.rcs": "941 914 814 R.C.S. Paris",
  "mentions_legales.hebergement.title": "Hébergement",
  "mentions_legales.hebergement.nom": "O2switch",
  "mentions_legales.hebergement.siret": "Siret : 510 909 807 00032",
  "mentions_legales.hebergement.rcs": "RCS Clermont Ferrand",
  "mentions_legales.hebergement.capital": "SAS au capital de 100 000€",
  "mentions_legales.presentation.title": "Présentation corporate",
  "mentions_legales.presentation.lien": "Télécharger la présentation corporate (PDF)",
  "mentions_legales.pi.title": "Propriété intellectuelle",
  "mentions_legales.pi.text": "L'ensemble du contenu de ce site est protégé par le droit d'auteur. Toute reproduction, même partielle, est interdite sans autorisation préalable.",

  # Confidentialité
  "confidentialite.title": "Politique de confidentialité",
  "confidentialite.responsable.title": "Responsable du traitement",
  "confidentialite.responsable.text": "Mentivis SAS, en sa qualité de responsable de traitement, s'engage à protéger vos données personnelles.",
  "confidentialite.donnees.title": "Données collectées",
  "confidentialite.donnees.text": "Nous collectons uniquement les données nécessaires à l'exécution de nos services : nom, email, téléphone, et informations relatives à votre entreprise.",
  "confidentialite.utilisation.title": "Utilisation des données",
  "confidentialite.utilisation.intro": "Vos données sont utilisées pour :",
  "confidentialite.utilisation.1": "Répondre à vos demandes de contact",
  "confidentialite.utilisation.2": "Vous informer sur nos services",
  "confidentialite.utilisation.3": "Exécuter les prestations commandées",
  "confidentialite.droits.title": "Vos droits",
  "confidentialite.droits.text": "Conformément au RGPD, vous disposez d'un droit d'accès, de rectification, d'effacement et de portabilité de vos données. Pour exercer ces droits, contactez-nous à privacy@icia.fr.",
  "confidentialite.duree.title": "Durée de conservation",
  "confidentialite.duree.text": "Vos données sont conservées pendant la durée de notre relation contractuelle et jusqu'à 3 ans après votre dernier contact.",
  "confidentialite.cookies.title": "Cookies et mesure d'audience",
  "confidentialite.cookies.text": "Ce site utilise Google Analytics pour mesurer l'audience et comprendre comment les visiteurs interagissent avec notre site.",
  "confidentialite.cookies.finalite": "Finalité",
  "confidentialite.cookies.finalite_text": "mesure d'audience, analyse du trafic et amélioration du site",
  "confidentialite.cookies.utilises": "Cookies utilisés",
  "confidentialite.cookies.utilises_text": "_ga, _gid, _gat (Google Analytics)",
  "confidentialite.cookies.duree": "Durée de conservation",
  "confidentialite.cookies.duree_text": "jusqu'à 13 mois",
  "confidentialite.cookies.consentement": "Consentement",
  "confidentialite.cookies.consentement_text": "les cookies analytiques ne sont activés qu'après votre consentement explicite via le bandeau de cookies. Vous pouvez modifier vos préférences à tout moment via le lien \"Gestion des cookies\" en bas de page.",

  # Conditions
  "conditions.title": "Conditions d'utilisation",
  "conditions.acceptation.title": "Acceptation des conditions",
  "conditions.acceptation.text": "En utilisant ce site, vous acceptez sans réserve les présentes conditions d'utilisation.",
  "conditions.utilisation.title": "Utilisation du site",
  "conditions.utilisation.text": "Le site est destiné à informer sur les services de l'Institut de l'IA. Toute utilisation à des fins illégales ou contraires à l'esprit du site est interdite.",
  "conditions.pi.title": "Propriété intellectuelle",
  "conditions.pi.text": "Tous les contenus présents sur ce site (textes, images, logos) sont protégés par le droit d'auteur. Toute reproduction est interdite sans autorisation.",
  "conditions.responsabilite.title": "Limitation de responsabilité",
  "conditions.responsabilite.text": "Les informations présentées sur ce site sont fournies à titre indicatif. L'Institut de l'IA ne saurait être tenu responsable des dommages résultant de l'utilisation du site.",
  "conditions.droit.title": "Droit applicable",
  "conditions.droit.text": "Les présentes conditions sont régies par le droit français. Tout litige sera soumis aux tribunaux compétents.",

  # Cookies
  "cookies.title": "Politique de cookies",
  "cookies.definition.title": "Qu'est-ce qu'un cookie ?",
  "cookies.definition.text": "Un cookie est un fichier texte déposé sur votre ordinateur lors de votre visite sur un site web. Il permet de mémoriser vos préférences et d'améliorer votre expérience de navigation.",
  "cookies.utilises.title": "Cookies utilisés",
  "cookies.utilises.text": "Notre site utilise des cookies strictement nécessaires au fonctionnement du site et des cookies analytiques pour mesurer l'audience.",
  "cookies.essentiels": "Cookies essentiels",
  "cookies.essentiels_text": "nécessaires au bon fonctionnement du site",
  "cookies.analytiques": "Cookies analytiques",
  "cookies.analytiques_text": "nous aident à comprendre comment vous utilisez le site",
  "cookies.gestion.title": "Gestion des cookies",
  "cookies.gestion.text": "Vous pouvez configurer votre navigateur pour refuser les cookies. Cependant, certaines fonctionnalités du site pourraient ne plus fonctionner correctement.",
}

with open('/Users/stv/Documents/zed/icia/content/site.txt', 'a') as f:
    for key, value in content.items():
        f.write(f'# {key}\n')
        f.write(f'{value}\n\n')

print(f"Appended {len(content)} keys")
